import "./globals.css";
import { Lexend_Deca } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";

const lexendDeca = Lexend_Deca({
  subsets: ["latin"],
  style: "normal",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="dark" lang="en">
      <body className={`bg-slate-900 ${lexendDeca.className}`}>
        <AuthProvider>
          <section className="container mx-auto h-screen py-10">
            <div className="rounded-lg shadow animate-fade overflow-hidden h-full relative bg-slate-800">
              {children}
            </div>
          </section>
        </AuthProvider>
      </body>
    </html>
  );
}
