import "./globals.css";
import { Lexend_Deca } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";

const lexendDeca = Lexend_Deca({
  subsets: ["latin"],
  style: "normal",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="dark" lang="en">
      <body className={`bg-neutral-800 ${lexendDeca.className}`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
